### ISSUE TITLE
UI Controls - please show them even when not in pose mode

### ISSUE THREAD

**Issue by LarsJandel** [RxLaboratory/Bluik#36]
Currently the **UI Controls** are only visible in the _N-Panel_ when being in _Pose Mode_. It would be nice to have them accessible in the other modes as well, e.g. to control geo masks, to show / hide specified geometry. Thanks

**Comment by Nico-Duduf** [comment]
Hi,

When you say "other modes", you're talking about the edit mode right?

In object mode, I don't know what can be done, as UI Controls are assigned to bones. But we could just show all UI controls in object mode?

**Comment by LarsJandel** [comment]
Both other modes, edit and object would be nice, similar as the Duik Layers are always visible. Hm, I see what you are saying regarding "assigned to bones", so yes, it would mean to show all the UI Controls of all bones in the other modes as you proposed. Worth a try, if you like the idea. As the Controls already have a collapse/expand toggle, the user can just collapse them if it's getting a long list. Thanks

**Comment by Nico-Duduf** [comment]
Done ;)
v0.7.0

**Comment by LarsJandel** [comment]
🎉 Thanks! You just forgot to add the _proper_ zip for the installation in the release 🙄😅

**Comment by Nico-Duduf** [comment]
Yup, we're migrating from Github to Codeberg!
The releases are now hosted there: https://codeberg.org/RxLaboratory/Bluik/releases
(we keep a mirror on Github for some time, but don't upload releases ;) )

**Comment by SuitableForWork** [comment]
It's very encouraging to see how active the devs here :)

Simple things like this are the kind of thing that makes me want to donate. Keep up the great work!
